[project]
name = "confidence"
version = "0.1.0"
description = "LLM metacognitive confidence project"
readme = "README.md"
requires-python = "==3.11.*"

dependencies = [
    "vllm==0.23.0",
    "trl==1.7.*",

    "deepspeed",
    "transformers",
    "accelerate",
    "datasets",
    "peft",
    "pyphi @ git+https://github.com/wmayner/pyphi.git@feature/iit-4.0",

    "scikit-learn",
    "tensorboard",
    "torch-tb-profiler",
    "bitsandbytes",
    "math-verify",
    "matplotlib",
    "huggingface-hub",
    "metadpy",
    "arviz",
    "opencv-python-headless>=4.10,<5",
]

